set(LLVM_ENABLE_RUNTIMES "libcxx;libcxxabi;libunwind" CACHE STRING "" FORCE)

set(LIBCXX_CXX_ABI "libcxxabi" CACHE STRING "" FORCE)
set(LIBCXX_ENABLE_SHARED             TRUE CACHE BOOL "" FORCE)
set(LIBCXX_ENABLE_STATIC             TRUE CACHE BOOL "" FORCE)
set(LIBCXX_ENABLE_STATIC_ABI_LIBRARY FALSE CACHE BOOL "" FORCE)
set(LIBCXXABI_ENABLE_SHARED          TRUE CACHE BOOL "" FORCE)
set(LIBCXXABI_ENABLE_STATIC          TRUE CACHE BOOL "" FORCE)
set(LIBUNWIND_ENABLE_SHARED          TRUE CACHE BOOL "" FORCE)
set(LIBUNWIND_ENABLE_STATIC          TRUE CACHE BOOL "" FORCE)

set(LIBCXXABI_USE_LLVM_UNWINDER      TRUE CACHE BOOL "" FORCE)
set(LIBCXXABI_USE_COMPILER_RT        TRUE CACHE BOOL "" FORCE)
set(LIBCXX_HAS_MUSL_LIBC             TRUE CACHE BOOL "" FORCE)

set(LIBCXX_INCLUDE_TESTS             FALSE CACHE BOOL "" FORCE)
set(LIBCXX_INCLUDE_BENCHMARKS        FALSE CACHE BOOL "" FORCE)
