#!/usr/bin/env sh
set -e
cd "$(dirname "$0")"
. ./config
export PATH="$OUTPUT_DIR/bin:$PATH"

BUILD_DIR=".build/compiler-rt"
(test -d $BUILD_DIR && rm -rf $BUILD_DIR) || true
mkdir -p $BUILD_DIR && cd $BUILD_DIR

COMPILER_RT_INSTALL_PREFIX="$("$OUTPUT_DIR/bin/clang" --print-resource-dir)"
COMPILER_RT_CMAKE_FLAGS=""
COMPILER_RT_CFLAGS="-fdebug-default-version=4 -gdwarf-4 -march=armv8.3-a+pauth -mbranch-protection=pauthabi"

if [ -z "$COMPILER_RT_FULL_BUILD" ]; then
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_LIBFUZZER=OFF -DCOMPILER_RT_BUILD_MEMPROF=OFF -DCOMPILER_RT_BUILD_PROFILE=OFF"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_SANITIZERS=OFF -DCOMPILER_RT_BUILD_XRAY=OFF -DCOMPILER_RT_BUILD_ORC=OFF"
  COMPILER_RT_CFLAGS="$COMPILER_RT_CFLAGS -nostdlib"
else
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_BUILTINS=OFF -DSANITIZER_CXX_ABI=libc++"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_SANITIZERS=OFF -DCOMPILER_RT_BUILD_XRAY=OFF -DCOMPILER_RT_BUILD_MEMPROF=OFF -DLIBCXX_HAS_MUSL_LIBC=ON"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_USE_BUILTINS_LIBRARY=TRUE"
fi

COMPILER_RT_SRC_DIR=$LLVM_SOURCE_DIR/compiler-rt

CFLAGS="$COMPILER_RT_CFLAGS" CXXFLAGS="$COMPILER_RT_CFLAGS" "$CMAKE_WRAPPER" $CROSS_TARGET \
  -S $COMPILER_RT_SRC_DIR \
  -DCMAKE_INSTALL_PREFIX="$COMPILER_RT_INSTALL_PREFIX" \
  -DCMAKE_C_COMPILER_WORKS=1 \
  -DCMAKE_CXX_COMPILER_WORKS=1 \
  -DCMAKE_C_COMPILER_TARGET=$CROSS_TARGET \
  -DCMAKE_CXX_COMPILER_TARGET=$CROSS_TARGET \
  -DCMAKE_ASM_COMPILER_TARGET=$CROSS_TARGET \
  -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
  -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
  $COMPILER_RT_CMAKE_FLAGS

cmake --build . --target install -- -j$CPU_COUNT

normalized_triple=$("$OUTPUT_DIR/bin/$CROSS_TARGET-clang" --print-target-triple)
ln -sfn $CROSS_TARGET "$COMPILER_RT_INSTALL_PREFIX/lib/$normalized_triple"
