#!/usr/bin/env sh
set -e
cd "$(dirname "$0")"
. ./config

BUILD_DIR=".build/compiler-rt"
(test -d $BUILD_DIR && rm -rf $BUILD_DIR) || true
mkdir -p $BUILD_DIR && cd $BUILD_DIR

COMPILER_RT_INSTALL_PREFIX="$("$INSTALL_DIR/bin/clang" --print-resource-dir)"
COMPILER_RT_CMAKE_FLAGS=""

if [ -z "$COMPILER_RT_FULL_BUILD" ]; then
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_LIBFUZZER=OFF -DCOMPILER_RT_BUILD_MEMPROF=OFF -DCOMPILER_RT_BUILD_PROFILE=OFF"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_SANITIZERS=OFF -DCOMPILER_RT_BUILD_XRAY=OFF -DCOMPILER_RT_BUILD_ORC=OFF"
  RT_EXTRA_FLAGS="$RT_EXTRA_FLAGS -nostdlib"
else
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_BUILTINS=OFF -DSANITIZER_CXX_ABI=libc++"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_BUILD_SANITIZERS=OFF -DCOMPILER_RT_BUILD_XRAY=OFF -DCOMPILER_RT_BUILD_MEMPROF=OFF -DLIBCXX_HAS_MUSL_LIBC=ON"
  COMPILER_RT_CMAKE_FLAGS="$COMPILER_RT_CMAKE_FLAGS -DCOMPILER_RT_USE_BUILTINS_LIBRARY=TRUE"
fi

cmake \
  -DTOOLCHAIN_BUILD_INSTALL_DIR="$INSTALL_DIR" \
  -DTOOLCHAIN_BUILD_TARGET="$CROSS_TARGET" \
  -DTOOLCHAIN_BUILD_EXTRA_RUNTIME_FLAGS="$RT_EXTRA_FLAGS" \
  --toolchain ../../toolchain-file.cmake \
  -S $LLVM_SOURCE_DIR/compiler-rt \
  -DCMAKE_INSTALL_PREFIX="$COMPILER_RT_INSTALL_PREFIX" \
  -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
  -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON \
  $COMPILER_RT_CMAKE_FLAGS

cmake --build . --target install -- -j$CPU_COUNT

normalized_triple=$("$INSTALL_DIR/bin/$CROSS_TARGET-clang" --print-target-triple)
ln -sfn $CROSS_TARGET "$COMPILER_RT_INSTALL_PREFIX/lib/$normalized_triple"
