set(COMPILER_RT_BUILD_BUILTINS       FALSE CACHE BOOL "" FORCE)
set(COMPILER_RT_USE_BUILTINS_LIBRARY TRUE CACHE BOOL "" FORCE)
set(LIBCXX_HAS_MUSL_LIBC             TRUE CACHE BOOL "" FORCE)

set(SANITIZER_CXX_ABI "libc++" CACHE STRING "" FORCE)
