set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON  CACHE BOOL "" FORCE)
set(COMPILER_RT_DEFAULT_TARGET_ONLY    ON  CACHE BOOL "" FORCE)

set(COMPILER_RT_BUILD_SANITIZERS       OFF CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_XRAY             OFF CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_MEMPROF          OFF CACHE BOOL "" FORCE)
