set(CMAKE_BUILD_TYPE       "Release" CACHE STRING "" FORCE)
set(LLVM_ENABLE_ASSERTIONS FALSE     CACHE BOOL   "" FORCE)
set(LLVM_CCACHE_BUILD      TRUE      CACHE BOOL   "" FORCE)
set(LLVM_LINK_LLVM_DYLIB   TRUE      CACHE BOOL   "" FORCE)
set(CLANG_LINK_CLANG_DYLIB TRUE      CACHE BOOL   "" FORCE)

set(LLVM_ENABLE_PROJECTS  "clang;lld" CACHE STRING "" FORCE)
set(LLVM_TARGETS_TO_BUILD "AArch64"   CACHE STRING "" FORCE)

set(LLVM_ENABLE_TERMINFO FALSE      CACHE BOOL   "" FORCE)
set(LLVM_ENABLE_LIBXML2  "FORCE_ON" CACHE STRING "" FORCE)
set(LLVM_ENABLE_THREADS  FALSE      CACHE BOOL   "" FORCE)

set(CLANG_DEFAULT_RTLIB        "compiler-rt"        CACHE STRING "" FORCE)
set(CLANG_DEFAULT_LINKER       "lld"                CACHE STRING "" FORCE)
set(CLANG_DEFAULT_CXX_STDLIB   "libc++"             CACHE STRING "" FORCE)
set(LLVM_DEFAULT_TARGET_TRIPLE "aarch64-linux-musl" CACHE STRING "" FORCE)
