set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR TRUE  CACHE BOOL "" FORCE)
set(COMPILER_RT_DEFAULT_TARGET_ONLY    TRUE  CACHE BOOL "" FORCE)

set(COMPILER_RT_BUILD_SANITIZERS       FALSE CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_XRAY             FALSE CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_MEMPROF          FALSE CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_ORC              FALSE CACHE BOOL "" FORCE)
