set(COMPILER_RT_EXCLUDE_ATOMIC_BUILTIN FALSE CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_LIBFUZZER        FALSE CACHE BOOL "" FORCE)
set(COMPILER_RT_BUILD_PROFILE          FALSE CACHE BOOL "" FORCE)

# This is set before the toolchain file is parsed.
string(APPEND TOOLCHAIN_BUILD_EXTRA_RUNTIME_FLAGS " -nostdlib")
