# Variables used by this toolchain file:
# - TOOLCHAIN_BUILD_INSTALL_DIR
# - TOOLCHAIN_BUILD_TARGET
# - TOOLCHAIN_BUILD_EXTRA_RUNTIME_FLAGS

set(CMAKE_SYSTEM_NAME  "Linux" CACHE STRING "")

set(CMAKE_C_COMPILER   "${TOOLCHAIN_BUILD_INSTALL_DIR}/bin/${TOOLCHAIN_BUILD_TARGET}-clang" CACHE STRING "")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_BUILD_INSTALL_DIR}/bin/${TOOLCHAIN_BUILD_TARGET}-clang++"  CACHE STRING "")
set(CMAKE_AR           "${TOOLCHAIN_BUILD_INSTALL_DIR}/bin/${TOOLCHAIN_BUILD_TARGET}-ar" CACHE STRING "")
set(CMAKE_RANLIB       "${TOOLCHAIN_BUILD_INSTALL_DIR}/bin/${TOOLCHAIN_BUILD_TARGET}-ranlib" CACHE STRING "")
set(CMAKE_STRIP        "${TOOLCHAIN_BUILD_INSTALL_DIR}/bin/${TOOLCHAIN_BUILD_TARGET}-strip" CACHE STRING "")

set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE CACHE BOOL "")

set(CMAKE_C_COMPILER_WORKS   TRUE CACHE BOOL "")
set(CMAKE_CXX_COMPILER_WORKS TRUE CACHE BOOL "")

set(CMAKE_C_COMPILER_TARGET   "${TOOLCHAIN_BUILD_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "${TOOLCHAIN_BUILD_TARGET}" CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET "${TOOLCHAIN_BUILD_TARGET}" CACHE STRING "")

set(TOOLCHAIN_BUILD_FLAGS "-fdebug-default-version=4 -gdwarf-4 -march=armv8.3-a+pauth ${TOOLCHAIN_BUILD_EXTRA_RUNTIME_FLAGS}")
set(CMAKE_CXX_FLAGS "${TOOLCHAIN_BUILD_FLAGS}" CACHE STRING "")
set(CMAKE_C_FLAGS   "${TOOLCHAIN_BUILD_FLAGS}" CACHE STRING "")
set(CMAKE_ASM_FLAGS "${TOOLCHAIN_BUILD_FLAGS}" CACHE STRING "")
